create table world_data(
    "countries" varchar(100) not null,
    "Population(millions) mid-2020" float,
    "Births per 1,000 Population" Int,
    "Deaths per 1,000 Population" Int,
    "Rate of Natural Increase (%)" Float,
    "Net Migration Rate" Int, 
    "Population(millions) mid-2035" float,
    "Population(millions) mid-2050" float,
    "Infant Mortality Rate" Float, 
    "Total Mortality Rate" Float,
    "Population(%) mid-2020 Ages <15" Float,
    "Population(%) mid-2020 Ages 65+" Float,
    "Family Planning Among Married Women Ages 15-49c (All Methods)" Int,
    "Family Planning Among Married Women Ages 15-49c (Modern Methods)" Int,
    "Family Planning Among Married Women Ages 15-49c (Demand Satisfied by Modern Methods)" Int,
    "Life Expectancy By Year (All)" Int,
    "Life Expectancy By Year (Male)" Int,
    "Life Expectancy By Year (Female)" Int,
    "Ages 15+ With HIV/AIDS (%), 2018 (Male)" varchar(20),
    "Ages 15+ With HIV/AIDS (%), 2018 (Female)" varchar(20),
    "Urban Population (%)" Int,
    "Population in Cities of 1 Million+ (%)" Int,
    "Average Household Size" Float,
    "Population per km^2 of Arable Land" Int, 
    "GNI per Capita, PPP, 2018" Int
);